### ISSUE TITLE
[ERROR] Code error: Requesting too quickly!

### ISSUE THREAD

**Issue by shungo27** [SynTexDZN/homebridge-syntex-tuya#7]
**Describe the bug**
I get an error every time start Homebridge. But the plugin is working.

[ERROR] Code error: Requesting too quickly!

What is this error? 

**Config**
```
{
    "platform": "SynTexTuya",
    "name": "SynTexTuya",
    "logDirectory": "./SynTex/log",
    "port": 1713,
    "language": "us",
    "debug": false,
    "options": {
        "username": "xxxxx",
        "password": "xxxxx",
        "countryCode": "81",
        "platform": "smart_life",
        "discoverScenes": false
    }
}
```
**Logs**
```
[SynTexTuya] [DEBUG] Existing accessory found! [Smart plug] ( 42122031840d8e8bd26c )
[SynTexTuya] [DEBUG] Existing information-service found! [Smart plug] ( 42122031840d8e8bd26c )
[SynTexTuya] [DEBUG] Existing service found! [name: Smart plug, type: switch, letters: 40] ( 42122031840d8e8bd26c )
[SynTexTuya] [READ] HomeKit state of [Smart plug] is [true] ( 42122031840d8e8bd26c )
[SynTexTuya] [DEBUG] [Smart plug] was added to the system! ( 42122031840d8e8bd26c )
[SynTexTuya] [DEBUG] Refreshing device states ..
[SynTexTuya] [ERROR] Code error: Requesting too quickly! ( "you can discovery once in 600 seconds" ) ( [tuyawebapi.js] at line [88] )
Error: Requesting too quickly! ( "you can discovery once in 600 seconds" )
    at /Users/xxxxx/.nodebrew/node/v14.15.5/lib/node_modules/homebridge-syntex-tuya/tuyawebapi.js:88:13
    at /Users/xxxxx/.nodebrew/node/v14.15.5/lib/node_modules/homebridge-syntex-tuya/tuyawebapi.js:342:5
    at Request._callback (/Users/xxxxx/.nodebrew/node/v14.15.5/lib/node_modules/homebridge-syntex-tuya/tuyawebapi.js:329:5)
    at Request.self.callback (/Users/xxxxx/.nodebrew/node/v14.15.5/lib/node_modules/homebridge-syntex-tuya/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/Users/xxxxx/.nodebrew/node/v14.15.5/lib/node_modules/homebridge-syntex-tuya/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/Users/xxxxx/.nodebrew/node/v14.15.5/lib/node_modules/homebridge-syntex-tuya/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
```

**More Information**
 - OS: macOS 10.13.6
 - Node Version 14.15.5

**Comment by SynTexDZN** [comment]
This is not really a big deal. The problem is that the API only accepts requests every 600 seconds. So when your devices restarts and you have no pollingInterval defined that is bigger than 1200 seconds ( or you make too many restarts ) it shows this error. But after you wait for 600 seconds the devices should fetch correctly.
